#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  pythonPremierProgrammeTurtle.py
#  
#  Copyright 2014 Loïc Ordono>
#  
from turtle import *
from random import randrange

#on donne un nom a notre tortue
martha = Turtle()
#On definit un ecran
scene = Screen()
scene.setup(width=0.5, height=1.0, startx=0, starty=0) 
# width vraie dimension si entier, proportion de l'ecran si decimal
# startx entier, position de l'ecran par rapport a la gauche.

a=0
while 1:
        reset()
        couleur=input("entrez la couleur du triangle a dssinner: ")
        up()
        left(randrange(0,300))
        goto(randrange(0,200),randrange(0,200))
        backward(randrange(0,50))
        forward(randrange(0,40))
        down()
        color(couleur)
        forward(150)
        left(120)
        forward(150)
        left(120)
        forward(150)
        quitter=input("voulez-vous quitter? o/n: ")
        if quitter=="o" or quitter=="0":
            break

exitonclick()
